[package]
name = "bx"
version = "0.1.0"
authors = ["Dock O'Neal <mail@dockoneal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bauxite = "0.1.0"
clap = "2.33.0"
